#!/usr/bin/zsh
# This hook is run after every virtualenv is activated.

proj_name=$(echo $VIRTUAL_ENV|awk -F'/' '{print $NF}')
locs=("src" "simpleoncall" "underdog")
for loc in "${locs[@]}";
do
    if [ -d ~/$loc/$proj_name ]
    then
        cd ~/$loc/$proj_name
        break
    fi
done;
rehash
